spring:
    r2dbc:
        url: r2dbc:mysql://localhost:3306/vote
        username: root
        password: dPdmsdk?0928
    datasource:
        driver-class-name: io.r2dbc.spi.ConnectionFactory
    application:
        name: vote

r2dbc:
    pool:
        enabled: true
        max-size: 20
    my:
        connection:
            validation-query: "SELECT 1"
