spring:
    main:
        allow-bean-definition-overriding: true

    r2dbc:
        url: r2dbc:mysql://localhost:3306/vote
        username: root
        password: dPdmsdk?0928

r2dbc:
    pool:
        enabled: true
        max-size: 20
